; Configuration Settings
apiBaseUrl=https://marketplace-api.sshopencloud.eu/api/
apiOverview='item-search?categories=tool-or-service&f.keyword=DARIAH Resource&order=label'
apiOverviewCore='item-search?categories=tool-or-service&f.keyword=DARIAH Core Service&order=label'
apiDetail=tools-services/
wpBaseUrl=http://localhost:8888/dh-api
wpUpdatePage=tools-and-services/?update
wpListPage=tools-and-services/
wpDetailPage=tools-services-detail-view/
